---

- name: Add testing
  ansible.builtin.apt_repository:
    repo: "{{ item.releases}}"
    state: present
    filename: debian
  loop:
    - { releases: "deb http://deb.debian.org/debian/ testing main contrib non-free non-free-firmware" }
    - { releases: "deb-src http://deb.debian.org/debian/ testing main contrib non-free non-free-firmware" }
    - { releases: "deb http://deb.debian.org/debian/ testing-updates main contrib non-free non-free-firmware" }
    - { releases: "deb-src http://deb.debian.org/debian/ testing-updates main contrib non-free non-free-firmware" }
    - { releases: "deb http://security.debian.org/debian-security testing-security main contrib non-free non-free-firmware" }
    - { releases: "deb-src http://security.debian.org/debian-security testing-security main contrib non-free non-free-firmware" }
