---
# tasks file for service-telegram-ssh-tooling
# - name: Evaluating the authentication agent & adding the key...
#   shell: |
#     eval "$(ssh-agent)"
#     ssh-add {{ services_base_path_parent }}/.ssh/id_ed25519

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: "git@github.com:viperey/telegram-ssh-tooling.git"
    dest: "{{ base_path }}"
    key_file: "{{ services_base_path_parent }}/.ssh/id_ed25519"
    accept_hostkey: true
  become: yes
  become_user: "{{ destination_user }}"

- name: Create service data base folder
  file:
    path: "/etc/telegram-ssh-tooling"
    state: directory 
    owner: "{{ destination_user }}"
    group: "{{ destination_user }}"
    mode: u=rwX,g=rX,o=
    recurse: yes

- name: Install via SDKman
  shell: "cd {{ base_path }}; source {{ services_base_path_parent }}/.sdkman/bin/sdkman-init.sh && sdk env install"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ destination_user }}"

- name: Compile
  shell: "cd {{ base_path }}; source {{ services_base_path_parent }}/.sdkman/bin/sdkman-init.sh && sdk env install && sbt clean assembly"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ destination_user }}"

- copy:
    src: telegram-ssh-tooling.service
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: u=rwx,g=rwx,o=rwx

- name: Set service stuff
  shell: |
    systemctl daemon-reload
    systemctl enable telegram-ssh-tooling.service
    systemctl start telegram-ssh-tooling.service
  args:
    executable: /bin/bash

- name: Setup /etc/hosts.deny
  ansible.builtin.lineinfile:
    path: /etc/hosts.deny
    line: 'sshd: ALL'
    state: present

- name: Setup /etc/hosts.allow
  ansible.builtin.lineinfile:
    path: /etc/hosts.allow
    line: '{{ item.line }}'
    state: present
  loop:
    - { line: "sshd: 192.168.178.1/24" }
    - { line: "sshd: [fd00::]/16" }
