version: '3.4'
 
services:

  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
        - "80:80"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    networks:
        - default

networks:
  default:
    name: services_network
    external: true
