local map = vim.keymap.set

map("n", "<leader>dus", function()
  local widgets = require "dap.ui.widgets"
  local sidebar = widgets.sidebar(widgets.scopes)
  sidebar.open()
end, { desc = "Open debugging sidebar" })

map("n", "<leader>dc", function()
  require("dap").continue()
  require("dap").repl.open()
end)
map("n", "<leader>dr", function()
  require("dap").repl.toggle()
end)
map("n", "<leader>dK", function()
  require("dap.ui.widgets").hover()
end)
map("n", "<leader>dt", function()
  require("dap").toggle_breakpoint()
end)
map("n", "<leader>dso", function()
  require("dap").step_over()
end)
map("n", "<leader>dsi", function()
  require("dap").step_into()
end)
map("n", "<leader>dl", function()
  require("dap").run_last()
end)

map("n", "<leader>aa", require("telescope.builtin").diagnostics)
map("n", "gr", vim.lsp.buf.references, opts "Show references")
map("n", "gR", require("telescope.builtin").lsp_references, { desc = "[LSP] Show references in telescope" })
map("n", "gD", require("telescope.builtin").lsp_definitions)
map("n", "gi", require("telescope.builtin").lsp_implementations)
map("n", "gr", require("telescope.builtin").lsp_references)
map("n", "gy", require("telescope.builtin").lsp_incoming_calls)
