---
# tasks file for dotfiles

# - name: Print conditional variables
#   debug:
#     msg: "ansible_limit={{ ansible_limit }}; inventory_hostname={{ inventory_hostname }};"

# Copy
- name: Copy pulse autorandr configuration
  ansible.builtin.copy:
    src: "{{ ansible_limit }}/.dotfiles"
    dest: "{{ destination_user_home }}"
    owner: "{{destination_user}}"
    group: "{{destination_user}}"
    mode: u=rwx,g=rw,o=rw
  when: ansible_limit is defined and inventory_hostname == "pulse"

- name: "[Pulse] Link stuff for {{ item.target }} via stow"
  shell: "stow --adopt --verbose --target ~ {{ item.target }}"
  become: yes
  become_user: "{{ destination_user }}"
  args:
    chdir: "{{ destination_user_home }}/.dotfiles"
  loop:
    - { target: "autorandr" }
  when: ansible_limit is defined and inventory_hostname == "pulse"
