---

- name: Install oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ destination_user_home }}/.oh-my-zsh"
    force: false
  ignore_errors: true
  become: yes
  become_user: "{{ destination_user  }}"

- name: Change shell
  shell: "chsh -s /bin/zsh {{ destination_user  }}"
  become: yes
  become_user: root
